[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
swb-compiler = { path = "../swb-compiler" }
flat-html = { git = "https://github.com/BALD-rust/flat-html" }
less-html = { git = "https://github.com/BALD-rust/less-html" }
anyhow = "1.0.70"