[package]
name = "swb"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "./swb-shared",
    "./swb-demo",
    "./swb-compiler",
    "./example"
]

[[bin]]
name = "example"
path = "example/src/main.rs"