[package]
name = "swb-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.70", default-features = false }
ascii = { version = "1.1.0", default-features = false }

[features]
default = ["std"]
std = [
    "ascii/std",
    "ascii/alloc",
    "anyhow/std"
]