[package]
name = "swb-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
ascii = { version = "1.1.0", default-features = false, features = ["alloc"] }

[features]
default = ["std"]
std = [
    "ascii/std",
]